### ISSUE TITLE
 block-list-item defined but not used anywhere

### ISSUE THREAD

**Issue by kanru** [ingydotnet/swim-pgx#3]
Similar to block-code, I found that `block-list-item` is defined but not used. Is it a typo?

**Comment by ingydotnet** [comment]
This rule is referenced by the implementation code here:

https://github.com/ingydotnet/swim-pm/blob/master/lib/Swim/Tree.pm#L61
https://github.com/ingydotnet/swim-pm/blob/master/lib/Swim/Tree.pm#L77
https://github.com/ingydotnet/swim-pm/blob/master/lib/Swim/Tree.pm#L105
